---
title: "Emergency Brussels Sprouts"
type: "challenge"
description: "Implementing classes with composition"
depends: "rock-paper-scissors"
visibility: "assign"
ignore:
- "evening-oo-composition.md"
